#!/bin/bash
# FLAG: headupcommands

cd ~/Downloads
result=$(tree -f -i -Q | grep -i "flatpakref")
result=$(echo "$result" | head -1)
result=${result//\.\//};
result=${result//\"/};
	
if [ -z "$result" ];
then
	echo "No flatpakref file for flatpak installation found. You can now close this window."
	exit 1
fi;

echo "flatpak install $result"
echo 
	
flatpak install $result
	
echo
echo "Moving file '$result' to trash..."
gio trash $result
	
echo "All set! You can now close this window."
