#!/bin/bash

cd ~/.password-store

result=$(tree -f -i -Q | grep -i "$1")
result=$(echo "$result" | head -1)
result=${result[0]}
result=${result//.gpg/};
result=${result//"./"/};
result=${result//\"/};
result=$(pass show "$result" | grep -i "ssh");
result=${result//ssh /};

echo "Remote server: $result"

if [ -z "$2" ];
then
	ssh $result
else
	remote_command=${@:2};
	echo "Remote command: $remote_command"
	echo "--------------------------------------"
	
	ssh $result "$remote_command"
	exitcode="$?"
	echo 
	echo "Remote command exited with '$exitcode'"
fi;

echo "You can close this window"
