#!/bin/bash 

arg="$1"

perform_action() {

	if [[ "$arg" == "" ]];
	then
		exit $1
	elif [[ "$arg" == "off" ]];
	then
		echo "powering off..."
		systemctl poweroff
	elif [[ "$arg" == "poweroff" ]];
	then
		echo "powering off..."
		systemctl poweroff
	elif [[ "$arg" == "0" ]];
	then
		echo "powering off..."
		systemctl poweroff
	elif [[ "$arg" == "restart" ]];
	then
		echo "rebooting..."
		systemctl reboot
	elif [[ "$arg" == "reboot" ]];
	then
		echo "rebooting..."
		systemctl reboot
	elif [[ "$arg" == "boot" ]];
	then
		echo "rebooting..."
		systemctl reboot
	elif [[ "$arg" == "1" ]];
	then
		echo "rebooting..."
		systemctl reboot
	fi;
	
	exit $1

}

while [ true ]
do
	ranking=0
	apt_sessions=$(pstree | grep -i "apt")
	aptget_sessions=$(pstree | grep -i "apt-get")
	
	if [ -z "$apt_sessions" ];
	then ranking=$(($ranking+1))
	fi
	
	if [ -z "$aptget_sessions" ];
	then ranking=$(($ranking+1))
	fi
	
	if (( $ranking >= 2 ));
	then
		echo "idle"
		perform_action 1
        exit 0
	fi
	
	sleep 10
	
done
