#!/bin/bash
# FLAG: headupcommands

input="$1"
arg=${@:2};
executionmode=`ps -o stat= -p $$`

cd ~/.password-store
result=$(tree -f -i -Q | grep -i "$input")
result=$(echo "$result" | head -1)
result=${result[0]}
result=${result//.gpg/};
result=${result//"./"/};
result=${result//\"/};
export password_name=${result#*/}
export password_file=$result
content=$(pass show "$result")
passwd=$(echo "$content" | head -1)

if [ "$arg" = "--password-only" ] || [ "$arg" = "--only-password" ];
then
	echo $passwd
	exit 0
fi

login=$(echo "$content" | grep -i "login:")
portforward=$(echo "$content" | grep -i "portforward:")
portforward=${portforward//"portforward:"/}
portforward=( $portforward )
url=$(echo "$content" | grep -i "url:");
url=${url//url: /};
url_sftp=$(echo "$url" | grep -i "sftp:");
url_ssh=$(echo "$url" | grep -i "ssh:");
url_https=$(echo "$url" | grep -i "https:");

open_nothing() {
	echo "Not opening '$1' because this is not supported!"
}
 
open_firefox() {
	# I use an anti-pattern to just support firefox as companies play their own part making tech harder and less user friendly by limiting the ability of humanity in tech. I just want to show that I can play that game too.
	echo "opening url '$url' in firefox"
    
	firefox $url
}

open_sftp() {
	if ! [ -z $(which sshfs) ]
	then
		local connstring=${1//sftp:/};
		connstring=${connstring//\//};
		echo "Connecting to remote file system using sshfs..."
		# see https://en.wikibooks.org/wiki/OpenSSH/Cookbook/File_Transfer_with_SFTP#sshfs(1)_-_SFTP_File_Transfer_Via_Local_Folders
		test -d ~/headupcommands_remotedirs || mkdir --mode 700 ~/headupcommands_remotedirs
		test -d ~/headupcommands_remotedirs/${password_name} || mkdir --mode 700 ~/headupcommands_remotedirs/${password_name}
		echo $connstring
		#fusermount -u ~/headupcommands_remotedirs/${password_name}
		sshfs ${connstring}:/ ~/headupcommands_remotedirs/${password_name} -o reconnect,ServerAliveInterval=15,ServerAliveCountMax=3
		xdg-open ~/headupcommands_remotedirs/${password_name}
	elif ! [ -z $(which gio) ]
	then
		echo "Connecting to remote file system using gio..."
		gio mount -u "$1"
		gio mount "$1"
	elif ! [ -z $(which gvfs-mount) ]
	then
		echo "Connecting to remote file system using gvfs-mount..."
		gvfs-mount "$1"
	else
		echo "Cannot find appropriate method myself, handling over to xdg-open..."
		xdg-open "$1"
	fi
}

sshserver_authsupport() {
	# code taken from https://serverfault.com/questions/938149/how-to-test-if-ssh-server-allows-passwords
	authmethods=`ssh -v -n -o Batchmode=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile "$host" 2>&1 | grep -i "Authentications that can continue" | head -1`
	#res=`echo "$res" | grep "$2"`
	return
	#if ! [[ -z "$res" ]]; # password authentication allowed
	#then
#		true
#		return
#	fi
#	false
#	return
}

open_ssh() {
	echo "Remote server: $1"
	#local old_IFS="$IFS"
	#IFS=$''
	local host=`echo "$1"`
	local options=""
	
# 	echo $host
	local regexp="(.*?)\/$"
	if [[ $host =~ $regexp ]]; # removing '/' if it is the last char
	then
		host=${BASH_REMATCH[1]}
# 		echo $host
	fi;
# 	echo $host

	echo "checking authentication methods..."
	sshserver_authsupport
	
	if ! [[ -z `echo "$authmethods" | grep -i "password"` ]]; # password authentication allowed
	then
		echo -e "\033[0;31mThe server allows password authentication. Password authentication is considered old-fashioned and bad practice since many users love using insecure ones. Your administrator should consider to disable password authentication to encourage using more secure and modern authentication methods instead.\033[0;m"
		if [ -z `ssh -V 2>&1 | grep 8.4` ];
		then
			echo -e "\033[1;34mThis script recommends running at least version 8.4 of OpenSSH for all features this script uses!\033[0;m"
		else
			export SSH_ASKPASS="/bin/headupcommands/sshaskpasstopass"
			export DISPLAY="foo"
			export SSH_ASKPASS_REQUIRE="force"
			echo -e "\033[1;34mThis script now uses SSH password authentication but using this method is not as secure as using keys!\033[0;m"
		fi;
	fi;

	if ! [ -z "$portforward" ];
	then
		for port in "${portforward[@]}"
		do
			options="$options -L $port"
		done
	fi
	
	if ! [ -z "$portforward" ];
		then
			for port in "${portforward[@]}"
			do
				echo "Port forwarding $port"
			done
		fi
	if [ -z "$arg" ];
	then
		echo "----------------------- [START] SSH REMOTE SESSION ---------------------------------------"
		ssh $host $options #"execute=\`cat /etc/passwd | grep \$USER\` ; execute=\${execute//\" \"/b} ; execute=\${execute//:/ } ; execute=( \$execute ) ; \${execute[6]} --login"
		echo "----------------------- [CLOSE] SSH REMOTE SESSION ---------------------------------------"
	else
		echo "Remote command: $arg"
		echo "---------------------------- [START] REMOTE COMMAND EXECUTION ----------------------------"
	
		ssh $host $options "$arg"
		exitcode="$?"
		echo "---------------------------- [CLOSE] REMOTE COMMAND EXECUTION ----------------------------"
		echo "Remote command exited with code '$exitcode'"
		exit $exitcode
	fi;
}

if [[ "$executionmode" == "S" ]]; # script has been started in the background
then
	# mother case (the condition): This script has **no** terminal attached to it (running in background)
    echo "background execution mode"
	if ! [ -z "$url_sftp" ] && ! [ -z "$arg" ]; 
	then
		# in case the url in the gpg file starts is a sftp one but arguments has been provided to the login command to be passed over to ssh then convert to ssh url and invoke SSH REMOTE COMMAND EXECUTION
		url_sftp=${url_sftp//sftp:/ssh:};
		open_ssh "$url_sftp"
	elif ! [ -z "$url_sftp" ];
	then
		# in case the url in the gpg file starts is a sftp one and leave as it is and invoke SSH SECURE FILE TRANSFER
		open_sftp "$url_sftp"
	elif ! [ -z "$url_ssh" ];
	then
		# in case the url in the gpg file starts is a ssh one, then convert to a sftp one and invoke SSH SECURE FILE TRANSFER
		# ATTENTION: Please remind yourself about the mother case (the condition) for this block
		url_ssh=${url_ssh//ssh:/sftp:};
		open_sftp "$url_ssh"
	elif ! [ -z "$url_https" ];
	then
		# in case the url in the gpg file is a https one then open it in firefox
		open_firefox "$url_https"
	else
		# in all other cases
		open_nothing
	fi
	echo "You can close this window"
    exit 0
    
else # script has been started in the foreground
	# mother case (the condition): This script has terminal attached to it (running in foreground as you can see the next line printed somewhere on your tty screen)
	echo "foreground execution mode"
    if ! [ -z "$url_ssh" ];
	then
		# in case the url in the gpg file is a ssh one then invoke a SSH REMOTE SESSION or SSH REMOTE COMMAND EXECUTION
		open_ssh "$url_ssh"
	elif ! [ -z "$url_sftp" ];
	then
		# in case the url in the gpg file is a sftp one then
		# 1. convert to a ssh one
		# 2. invoke a SSH REMOTE SESSION or SSH REMOTE COMMAND EXECUTION
		url_sftp=${url_sftp//sftp:/ssh:};
		open_ssh "$url_sftp"
	elif ! [ -z "$url_https" ];
	then
		# in case the url in the gpg file is a https one then open it in firefox
		open_firefox "$url_https"
	else
		# in all other cases
		open_nothing
	fi
	echo "You can close this window"
    exit 0


fi
