#!/bin/bash
# FLAG: headupcommands

# this script approves fingerprints automatically and handles password authentication. This methodology is depending on your overall setup can be insecure but it isn't necessarily when done properly.

arg=$1

#echo "$arg" > "./test.txt"

password=`echo $arg | grep "password"`
sayyes=`echo $arg | grep "yes"`

if ! [[ -z "$password" ]];
then
	content=$(pass show "$password_file")
	passwd=$(echo "$content" | head -1)
	echo $passwd
fi;

if ! [[ -z "$sayyes" ]];
then
	echo "yes"
fi;

